In [52]:
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.tree import DecisionTreeClassifier as DTC
from sklearn.model_selection import cross_val_score

In [53]:
digits = datasets.load_digits()

In [54]:
X = digits.data
y = digits.target

In [55]:
print(X)
print(X.shape)

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]
(1797, 64)


In [56]:
print(y)
print(y.shape)
print(set(y))

[0 1 2 ... 8 9 8]
(1797,)
{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}


In [57]:
model = DTC()
cvs = cross_val_score(model, X, y, cv = 10)

In [58]:
np.mean(cvs)

0.8314627214291738

In [59]:
def write_answer_1(x):
    with open("answer1.txt", "w") as fout:
        fout.write(str(x))

In [60]:
write_answer_1(np.mean(cvs))

In [61]:
from sklearn.ensemble import BaggingClassifier as BC

In [62]:
model = BC(n_estimators = 100)
cvs = cross_val_score(model, X, y, cv = 10)

In [63]:
np.mean(cvs)

0.9259954063117375

In [64]:
def write_answer_2(x):
    with open("answer2.txt", "w") as fout:
        fout.write(str(x))
write_answer_2(np.mean(cvs))        

In [75]:
?DTC

In [66]:
model = BC(n_estimators = 100, max_features = int(np.sqrt(X.shape[1])))
cvs = cross_val_score(model, X, y, cv = 10)
np.mean(cvs)
def write_answer_3(x):
    with open("answer3.txt", "w") as fout:
        fout.write(str(x))
write_answer_3(np.mean(cvs)) 

In [67]:
np.mean(cvs)

0.9299030927896629

In [76]:
model = BC(base_estimator = DTC(max_features = int(np.sqrt(X.shape[1]))), n_estimators = 100)
cvs = cross_val_score(model, X, y, cv = 10)
np.mean(cvs)
def write_answer_4(x):
    with open("answer4.txt", "w") as fout:
        fout.write(str(x))
write_answer_4(np.mean(cvs))
np.mean(cvs)

0.95386418224502