# Sklearn

## sklearn.cross_validation

документация: http://scikit-learn.org/stable/modules/cross_validation.html

In [1]:
from sklearn import model_selection, datasets
import numpy as np

### Разовое разбиение данных на обучение и тест с помощью train_test_split

In [2]:
iris = datasets.load_iris()

In [4]:
train_data, test_data, train_labels, test_labels = model_selection.train_test_split(iris.data, iris.target, 
                                                                                     test_size = 0.3)

In [5]:
#убедимся, что тестовая выборка действительно составляет 0.3 от всех данных
float(len(test_labels))/len(iris.data)

0.3

In [7]:
print('Размер обучающей выборки: {} объектов \nРазмер тестовой выборки: {} объектов'.format(len(train_data),
                                                                                            len(test_data)))

Размер обучающей выборки: 105 объектов 
Размер тестовой выборки: 45 объектов


In [8]:
print('Обучающая выборка:\n', train_data[:5])
print('\n')
print('Тестовая выборка:\n', test_data[:5])

Обучающая выборка:
 [[5.7 2.5 5.  2. ]
 [5.6 2.5 3.9 1.1]
 [4.8 3.4 1.6 0.2]
 [5.  3.5 1.3 0.3]
 [7.7 3.8 6.7 2.2]]


Тестовая выборка:
 [[6.  3.4 4.5 1.6]
 [6.7 3.3 5.7 2.5]
 [4.9 2.4 3.3 1. ]
 [6.2 2.8 4.8 1.8]
 [4.9 3.1 1.5 0.1]]


In [9]:
print('Метки классов на обучающей выборке:\n', train_labels)
print('\n')
print('Метки классов на тестовой выборке:\n', test_labels)

Метки классов на обучающей выборке:
 [2 1 0 0 2 2 1 1 1 0 2 2 1 1 1 1 0 0 2 1 1 1 0 1 1 2 1 2 2 1 0 2 0 2 0 0 2
 0 1 0 2 1 1 0 1 0 2 1 2 0 1 0 1 1 0 2 1 0 2 1 0 0 0 0 2 0 1 2 0 0 0 2 2 0
 2 2 1 2 2 2 1 0 2 0 2 2 1 0 1 1 0 2 1 0 1 2 0 1 2 1 1 2 0 0 0]


Метки классов на тестовой выборке:
 [1 2 1 2 0 2 0 1 0 2 2 2 2 2 1 2 0 0 0 0 1 2 0 1 0 2 1 2 1 1 0 0 1 1 0 2 2
 2 2 0 1 1 0 1 2]


### Стратегии проведения кросс-валидации

#### KFold

In [15]:
for train_indices, test_indices in model_selection.KFold(n_splits = 5):
    print(train_indices, test_indices)

TypeError: 'KFold' object is not iterable

In [16]:
?model_selection.KFold

In [ ]:
for train_indices, test_indices in cross_validation.KFold(10, n_folds = 2, shuffle = True):
    print train_indices, test_indices

In [ ]:
for train_indices, test_indices in cross_validation.KFold(10, n_folds = 2, shuffle = True, random_state = 1):
    print train_indices, test_indices

#### StratifiedKFold

In [ ]:
target = np.array([0] * 5 + [1] * 5)
print target
for train_indices, test_indices in cross_validation.StratifiedKFold(target, n_folds = 2, shuffle = True, random_state = 0):
    print train_indices, test_indices

In [9]:
target = np.array([0, 1] * 5)
print(target)
for train_indices, test_indices in model_selection.StratifiedKFold(target, n_folds = 2,shuffle = True):
    print(train_indices, test_indices)

[0 1 0 1 0 1 0 1 0 1]


TypeError: __init__() got an unexpected keyword argument 'n_folds'

In [17]:
model_selection.StratifiedKFold?

#### ShuffleSplit

In [ ]:
for train_indices, test_indices in cross_validation.ShuffleSplit(10, n_iter = 10, test_size = 0.2):
    print train_indices, test_indices

In [13]:
model_selection.cross_val_score?

#### StratifiedShuffleSplit

In [ ]:
target = np.array([0] * 5 + [1] * 5)
print target
for train_indices, test_indices in cross_validation.StratifiedShuffleSplit(target, n_iter = 4, test_size = 0.2):
    print train_indices, test_indices

#### Leave-One-Out

In [ ]:
for train_indices, test_index in cross_validation.LeaveOneOut(10):
    print train_indices, test_index

Больше стратегий проведения кросс-валидации доступно здесь: http://scikit-learn.org/stable/modules/cross_validation.html#cross-validation-iterators